name: NBA Context Explorer

on: 
  workflow_dispatch:  # Manual trigger

jobs:
    explore:
        runs-on: ubuntu-latest
        steps:
          - name: Dump Github context
            env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
            run: echo "$GITHUB_CONTEXT"

          - name: Dump job context
            env: 
              JOB_CONTEXT: ${{ toJSON(job) }}
            run: echo "$JOB_CONTEXT"

          - name: Dump steps context
            env:
              STEP_CONTEXT: ${{ toJSON(steps) }}
            run: echo "$STEP_CONTEXT"

          - name: Dump runner context
            env:
              RUNNER_CONTEXT: ${{ toJSON(runner) }}
            run: echo "$RUNNER_CONTEXT"

          - name: Dump env context
            env:
              ENV_CONTEXT: ${{ toJSON(env) }}
            run: echo "$ENV_CONTEXT"

          - name: Dump workspace context
            env:
              WORKSPACE_CONTEXT: ${{ toJSON(workspace) }}
            run: echo "$WORKSPACE_CONTEXT"