
    name: Hello World

    on:
        push:
            branches:
            - main
        pull_request:
            branches:
            - main

    jobs:
        hello:
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v3
                - name: Hello NBA
                  run: echo "Welcome to the NBA GitHub Action Training Camp!"