name: NBA App Validation

on:
    push:
        paths:
          - 'projects/nba-stats-app/**'
    pull_request:
        paths:
          - 'projects/nba-stats-app/**'
          
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Check for required files
            run: |
              if [ -f "projects/nba-stats-app/index.html" ]; then
                echo " index.html found"
              else
                echo " index.html not found"
                exit 1
              fi

              if [ -f "projects/nba-stats-app/stats.js" ]; then
                echo " stats.js found"
              else
                echo " stats.js not found"
                exit 1
              fi

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '16'

          - name: Validate JavaScript syntax
            run: | 
              # Use grep to count the number of player objects
              PLAYER_COUNT=$(grep -c "name:" projects/nba-stats-app/stats.js)
              echo "Found $PLAYER_COUNT players in the data"
              if [ $PLAYER_COUNT -lt 2 ]; then 
                echo " Not enough players in the data"
                exit 1
              else
                echo " Player data looks good"
              fi

          - name: Check player stats completeness
            run: |
                node -e '
                  const stats = require("./projects/nba-stats-app/stats.js");
                  let missingStats = false;

                  stats.players.forEach(player => {
                    console.log(`Checking stats for ${player.name}:`);
                    const requiredStats = ["ppg", "rpg", "apg", "spg", "bpg"];
        
                    requiredStats.forEach(stat => {
                      if (player.stats[stat] === undefined) {
                        console.log(`❌ Missing ${stat} for ${player.name}`);
                        missingStats = true;
                      } else {
                        console.log(`✅ ${stat}: ${player.stats[stat]}`);
                      }
                    });
                  });
                        
                  if (missingStats) {
                    process.exit(1);
                  } else {
                    console.log("✅ All players have complete stats!");
                  }
                '